CFLAGS=-O3 -ffast-math -mavx2
CC=CC

all: ring_1.o ring_1 ring_1_d.o ring_1_d
ring_1.o: ring_1.c
ring_1: ring_1.o 
ring_1_d.o: ring_1_d.c
ring_1_d: ring_1_d
ring_2.o: ring_2.c 
ring_2: ring_2.o
clean: 
	rm ring_1.o ring_1 ring_1_d.o ring_1_d
